students/urls.py
from django.conf.urls import url 

urlpatterns = [
    url(r'^create-student/$', 'students.views.create_student', name='create_student'),
    url(r'^get-student/$', 'students.views.get_student', name='get_student'),
    url(r'^delete-student/$', 'students.views.delete_student', name='delete_student'),
    url(r'^edit-student/$', 'students.views.edit_student', name='edit_student'),
    url(r'^edit-actual-student/$', 'students.views.actual_edit', name='actual_edit'),
]

techno/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', 'students.views.homepage', name='homepage'),
    url(r'student/', include('students.urls')),
]

students/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


class Student(models.Model):
    user = models.ForeignKey(User)
    nationality = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return u'%s %s' %(self.user.first_name, self.user.last_name)

students/forms.py
from __future__ import unicode_literals
from datetime import datetime

from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from students.models import Student


class CreateStudentForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    nationality = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    def clean_email(self):
        try:
            existing_user = User.objects.get(email__iexact=self.cleaned_data['email'])
            if existing_user:
                self._errors["email"] = self.error_class(["Email already exist"])
        except User.MultipleObjectsReturned:
            self._errors["email"] = self.error_class(["Email already exist"])
        except:
            pass

        return self.cleaned_data['email']


class GetRequestForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    def clean_username(self):
        try:
            get_user = User.objects.get(username__iexact=self.cleaned_data['username'])
            
        except:
            self._errors["username"] = self.error_class(["Username doesn't exist"])

        return self.cleaned_data['username']


class GetDeleteForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    def clean_username(self):
        try:
            get_user = User.objects.get(username__iexact=self.cleaned_data['username'])
            
        except:
            self._errors["username"] = self.error_class(["Username doesn't exist"])    

        return self.cleaned_data['username']


class GetEditForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    def clean_username(self):
        try:
            get_user = User.objects.get(username__iexact=self.cleaned_data['username'])
            
        except:
            self._errors["username"] = self.error_class(["Username doesn't exist"])

        return self.cleaned_data['username']


class EditStudentForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    nationality = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)

  

students/views.py
import json

from django.shortcuts import render
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.db.models import Q
from django.core import serializers

from students.models import Student
from students.forms import CreateStudentForm, GetRequestForm, GetDeleteForm, GetEditForm, EditStudentForm
from students.utils import create_username
from django.forms.models import model_to_dict


from django.core.urlresolvers import reverse
from django.template.loader import render_to_string


def homepage(request):
    students = Student.objects.all()

    student_detail_content = []
    for student in students:
        student_detail_content.append(
            render_to_string('student/student_detail.html',{
                'student': student
                }, context_instance=RequestContext(request))
            )

    return render_to_response("student/homepage.html",{
        'student_detail_content': student_detail_content,
        'students':students,
        'create_student_form' : CreateStudentForm(),
        'get_request_form' : GetRequestForm(),
        'get_delete_form': GetDeleteForm(),
        'get_edit_form' : GetEditForm(),
        'edit_Student_form' : EditStudentForm(),
    }, context_instance=RequestContext(request))


def create_student(request):

    if request.is_ajax():

        response = {"status": False, "errors": []}

        if request.method == "POST":
            form= CreateStudentForm(request.POST)

            if form.is_valid():
                user = User.objects.create(
                    username=create_username('%s %s' % (form.cleaned_data["first_name"], form.cleaned_data["last_name"])),
                    first_name=form.cleaned_data["first_name"],
                    last_name=form.cleaned_data["last_name"],
                    email=form.cleaned_data["email"],
                )

                student = Student.objects.create(
                    user=user,
                    nationality=form.cleaned_data["nationality"]
                )

                user_id = student.user.id
                user = User.objects.get(id=user_id)

                response["status"] = True

                response["user_info"] = model_to_dict(user, fields=['username', 'first_name', 'last_name', 'email'])

                response["status"] = True

                response["student"] = render_to_string('student/student_detail.html', {
                    'student': student
                }, context_instance=RequestContext(request))

            else:
                for key, value in form.errors.items():
                    tmp = {'key': key, 'error': value.as_text()}
                    response['errors'].append(tmp)

        return HttpResponse(json.dumps(response))


def get_student(request):

    if request.is_ajax():
        response = {"status": False, "user_info":[], "student_info":[], "errors": []}

        if request.method == "POST":
            form = GetRequestForm(request.POST)

            if form.is_valid():

                student = Student.objects.get(
                    user__username = form.cleaned_data["username"]
                )

                user_id = student.user.id
                user = User.objects.get(id=user_id)

                response["status"] = True

                response["user_info"] = model_to_dict(user, fields=['username', 'first_name', 'last_name', 'email'])
                response["student_info"] = model_to_dict(student)
                
            else:
                for key, value in form.errors.items():
                        tmp = {'key': key, 'error': value.as_text()}
                        response['errors'].append(tmp)     

            return HttpResponse(json.dumps(response))


def delete_student(request):

    if request.is_ajax():
    
        response = {"status": False, "errors": []}

        if request.method == "POST":
            form = GetDeleteForm(request.POST)

            if form.is_valid():

                student = Student.objects.get(
                    user__username = form.cleaned_data["username"]
                )

                student.user.delete()
                student_id = student.id

                response["status"] = True
                response["student_deleted"] = model_to_dict(student, fields=['username', 'id'])
                response["status"] = True
                
            else:
                for key, value in form.errors.items():
                        tmp = {'key': key, 'error': value.as_text()}
                        response['errors'].append(tmp)     

            return HttpResponse(json.dumps(response))



def edit_student(request):

    if request.is_ajax():
        response = {"status": False, "errors": []}

        if request.method == "POST":
            form = GetEditForm(request.POST)

            if form.is_valid():

                student = Student.objects.get(
                    user__username = form.cleaned_data["username"]
                )

                response["status"] = True
                user_id = student.user.id
                user = User.objects.get(id=user_id)

                response["status"] = True

                response["student"] = model_to_dict(student, fields=['id', 'nationality'] )

                response["user_info"] = model_to_dict(user, fields=['username', 'first_name', 'last_name', 'email'])
            else:
                for key, value in form.errors.items():
                        tmp = {'key': key, 'error': value.as_text()}
                        response['errors'].append(tmp)

            return HttpResponse(json.dumps(response))



def actual_edit(request, student_id):

    student_id = request.Get.get('student_id', '')

    response = { "status": False, "errors":[] } 

    if request.method == "POST":

        form = EditStudentForm(request.POST)

        if form.is_valid():
            student.user.first_name = form.cleaned_data["first_name"]
            student.user.last_name = form.cleaned_data["last_name"]
            student.user.email = form.cleaned_data["email"]
            student.nationality = form.cleaned_data["nationality"]
            student.save()

            response["status"] = True

            response["student"] = render_to_string('student/student_detail.html', {
                'student': student
            }, context_instance=RequestContext(request))
        else:
            for key, value in form.errors.items():
                tmp = {'key': key, 'error': value.as_text()}
                response['errors'].append(tmp)

    return HttpResponse(json.dumps(response))

templates/student/homepage.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block javascript %}
    <script src="{% static 'js/bloodhound.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap-typeahead.js' %}"></script>
    <script type="text/javascript">

        
    </script>
{% endblock %}

{% block content %}
    <div class="container-fluid" style="margin-top: -20px;">
        <div class="row">
            <center><h3><strong>Data-Section</strong></h3></center> 
            <div class="col-md-10 col-md-offset-1 profile-block">
                <div id="id_added_students">
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table col-md-offset-1">
                                <td class="col-md-3 gap"><strong>Student Id</strong></td>
                                <td class="col-md-3 gap"><strong>User Name</strong></td>
                                <td class="col-md-3 gap"><strong>Email</strong></td>
                                <td class="col-md-3 gap"><strong>Full Name</strong></td>  
                            </table>
                            {% for student in student_detail_content %}
                                {{ student }}
                            {% endfor %}            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row" style="margin-top: 20px;">
        <div class="col-md-10 col-md-offset-1">
            <div class="btn-group btn-group-justified" role="group" aria-label="">
                <div class="btn-group" role="group">
                    <button id="add_more_student" type="button" class="btn btn-default" onclick="open_create()">Create</button>
                </div>
                <div class="btn-group" role="group">
                    <button type="button" id="edit_more_student" class="btn btn-default" onclick="open_edit()">Update</button>
                </div>
                <div class="btn-group" role="group">
                    <button type="button" id="delete_more_student" class="btn btn-default" onclick="open_delete()">Delete</button>
                </div>
                <div class="btn-group" role="group">
                    <button type="button" id="get_more_student" class="btn btn-default" onclick="open_get()">Get</button>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid" style="margin-top: 20px;">
        <div class="row">
            <h3 class="col-md-offset-1">Request Section</h3>
            <div class="col-md-4 col-md-offset-1 profile-block">
                <div id="id_students">
                    <form class="form-horizontal" id="id_create_student" action="{% if student_id %}{% url 'actual_edit' student_id %}{% else %}{% url 'create_student' %}{% endif %}" role="form" method="post" onsubmit="return save_student($(this))" style="display: none;">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group"  id="id_first_name_error_parent_div">
                                    <div class="col-md-12">
                                        <label for="id_first_name" class="control-label">*First Name:</label>
                                        {{ create_student_form.first_name }}
                                        <small class="error-msgs error" id="id_first_name_error" style="display: none;"></small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group"  id="id_last_name_error_parent_div">
                                    <div class="col-md-12">
                                        <label for="id_last_name" class="control-label">*Last Name:</label>
                                        {{ create_student_form.last_name }}
                                        <small class="error-msgs error" id="id_last_name_error" style="display: none;"></small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group"  id="id_email_error_parent_div">
                                    <div class="col-md-12">
                                        <label for="id_email" class="control-label">*Email:</label>
                                        {{ create_student_form.email }}
                                        <small class="error-msgs error" id="id_email_error" style="display: none;"></small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group"  id="id_nationality_error_parent_div">
                                    <div class="col-md-12">
                                        <label for="id_nationality" class="control-label">Nationality:</label>
                                        {{ create_student_form.nationality }}
                                        <small class="error-msgs error" id="id_nationality_error" style="display: none;"></small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group" style="border-width: -30px;">
                                    <div class="col-md-12">
                                        <div class=pull-left>
                                            <input class="btn btn-primary btn-sm reset" type="submit" value="Create" style="width: 80px;"/>
                                        </div>
                                        <div class=pull-right>
                                            <button class="btn btn-primary btn-sm" type="button"  style="width: 80px;" onclick="remove_form()">
                                                Cancel
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>  
                    </form>
                    <form class="form-horizontal" id="id_get_student" action="{% url 'get_student' %}" role="form" method="post" onsubmit="return fetch_student($(this))" style="display: none;">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group"  id="id_get_username_error_parent_div">
                                    <div class="col-md-12">
                                        <label for="id_get_user" class="control-label">*Username:</label>
                                        {{ get_request_form.username }}
                                        <small class="error-msgs error" id="id_get_username_error" style="display: none;"></small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group" style="border-width: -30px;">
                                    <div class="col-md-12">
                                        <div class=pull-left>
                                            <input class="btn btn-primary btn-sm reset" type="submit" value="Get Details" style="width: 80px;"/>
                                        </div>
                                        <div class=pull-right>
                                            <button class="btn btn-primary btn-sm" type="button"  style="width: 80px;" onclick="remove_form()">
                                                Cancel
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>  
                    </form>
                    <form class="form-horizontal" id="id_delete_student" action="{% url 'delete_student' %}" role="form" method="post" onsubmit="return remove_student($(this))" style="display: none;">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group"  id="id_delete_username_error_parent_div">
                                    <div class="col-md-12">
                                        <label for="id_get_delete" class="control-label">*Username:</label>
                                        {{ get_delete_form.username }}
                                        <small class="error-msgs error" id="id_delete_username_error" style="display: none;"></small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group" style="border-width: -30px;">
                                    <div class="col-md-12">
                                        <div class=pull-left>
                                            <input class="btn btn-primary btn-sm reset" type="submit" value="Delete" style="width: 80px;"/>
                                        </div>
                                        <div class=pull-right>
                                            <button class="btn btn-primary btn-sm" type="button"  style="width: 80px;" onclick="remove_form()">
                                                Cancel
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>  
                    </form>
                    <form class="form-horizontal" id="id_edit_student" action="{% url 'edit_student' %}" role="form" method="post" onsubmit="return update_student($(this))" style="display: none;">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group"  id="id_edit_username_error_parent_div">
                                    <div class="col-md-12">
                                        <label for="id_get_update" class="control-label">*Username:</label>
                                        {{ get_edit_form.username }}
                                        <small class="error-msgs error" id="id_edit_username_error" style="display: none;"></small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group" style="border-width: -30px;">
                                    <div class="col-md-12">
                                        <div class=pull-left>
                                            <input class="btn btn-primary btn-sm" type="submit" value="Next" style="width: 80px;"/>
                                        </div>
                                        <div class=pull-right>
                                            <button class="btn btn-primary btn-sm" type="button"  style="width: 80px;" onclick="remove_form()">
                                                Cancel
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>  
                    </form>
                </div>
            </div>
            <h3 class="col-md-4 col-md-offset-2" style="margin-top: -40px;">Response section</h3>
            <div class="col-md-4 col-md-offset-2 profile-block">
                <pre id="id_response"></pre>

            </div>
        </div>
    </div>
{% endblock %}

templates/student/student_detail.html
<div class="row"  id="id_student_{{ student.id }}">
    <div class="col-md-12 col-md-offset-1">
        <table class="table">
            <th class="col-md-3 gap" scope="row">{{ student.id }}</th>
            <td class="col-md-3 gap">{{ student.user.username }}</td>
            <td class="col-md-3 gap">{{ student.user.email }}</td>
            <td class="col-md-3 gap">{{ student.user.get_full_name }}</td>     
        </table>
    </div>
</div>